---
- name : Intall nginx on server
  hosts : webserver
  become : true
  tasks :
    - name : Install Nginx on Debian/Ubuntu
      ansible.builtin.apt :
        name : nginx
        state : present
        update cache: yes
       when : ansible_os_family == "Debian"
    - name : Install Nginx on Redhat/CentOS
      ansible.builtin.yum :
        name : nginx 
        state: present
        update cache : yes
      when : ansible_os_family == "RedHat"
    - name: Enable and start Nginx service
      ansible.builtin.service:
        name: nginx 
        state: started
        enabled : true 
